Add variable truth tutorial
LSSTDESC/desc-data-portal pull request #90
Opened 2022-03-10 19:36 UTC by yymao

This PR adds the variable truth tutorial and fixes #89. 

Feedback welcome.  There's a few cells that need to be removed before merging; I left them there for now so that the reviewer can run this notebook on NERSC more easily (you will need to use the `u/yymao/pr587-review` branch of `gcr-catalogs` for this notebook to work).

2022-06-07 13:13 UTC, yymao commented
I have updated this tutorial notebook to match the latest truth catalogs. It's now ready for review @JoanneBogart @wmwv

2022-06-08 00:57 UTC, JoanneBogart requested changes
Generally looks good!  I've made a number of minor suggestions - fixing typos, making the text more idiomatic or, in one or two cases, trying for more clarity.  Please also consider whether there is a way to make the variability in the  first star plot more evident.

2022-06-08 00:57 UTC, JoanneBogart commented on notebooks/dc2/truth_variable_info.ipynb
> +    "  2. Being able to load the light curves for any SNe or stars that are of interset. "
omit "being able to".   For 2. you just need "Load the light curves ..."

2022-06-08 00:57 UTC, JoanneBogart commented on notebooks/dc2/truth_variable_info.ipynb
> +    "We will start with finding light curves for supernovae.  When accessing DC2 variable truth information, one important concept is that the light curves are stored separetely from a \"summary tabl
separetely --> separately

2022-06-08 00:57 UTC, JoanneBogart commented on notebooks/dc2/truth_variable_info.ipynb
> +    "In the summary table, each row corresponds to one object (supernova), and it contains \"summary\" truth information such as coordinates, redshift, and time-averaged fluxes, but not the light cur
Maybe add a sentence like
"Here _summary_ implies associated with the source generally, not with a particular observation of the source." 
or modify the sentence you have:

In the summary table, each row corresponds to one object (here a supernova), and it contains _summary_ truth information such as coordinates, redshift, and time-averaged fluxes - that is, attributes associated with the object overall, not with a particular observation of it.  Hence it does not include light curve values.

2022-06-08 00:57 UTC, JoanneBogart commented on notebooks/dc2/truth_variable_info.ipynb
> +    "We will now actually load the data into memory. For this tutorial, we will only need the ID (`id`), coordinates (`ra`, `dec`), redshift. \n",
Replace comma before the word "redshift" with the word "and"

2022-06-08 00:57 UTC, JoanneBogart commented on notebooks/dc2/truth_variable_info.ipynb
> +    "Now that we have the summary table, we can use it to select, say supernovae near a certain coordinate or in a certain redshift range. In this tutorial, we will find all supernovae that are withi
Suggest ending sentence with
"all supernovae that are within 2 arcmin of (RA, Dec) = (60.5, -36.6) and satisfy z < 0.8."

2022-06-08 00:57 UTC, JoanneBogart commented on notebooks/dc2/truth_variable_info.ipynb
> +    "Unlike the summary table, in the variability table, each row corresponds to one \"measurement\" the flux of a given object, at a given time, with a given filter. Hence, a single supernovae may c
1. Should not be a comma after variability table.  2. There is a missing word ("of") or missing punctuation (colon) after "measurement".   3. "corresponds" is maybe not the best word here.   I suggest

Unlike the summary table, in the variability table each row corresponds to one "measurement": the flux of a given object, at a given time, with a given filter. Hence, a single supernova is usually represented by many rows.

2022-06-08 00:57 UTC, JoanneBogart commented on notebooks/dc2/truth_variable_info.ipynb
> +    "You can see that from above that the first five rows are all different measurements (at different time or with different filters) for a single object (`MS_9177_2005`). \n",
Suggest
You can see from the above the the first five rows are all different measurements (at different times and not always with the same filter) for a single...

2022-06-08 00:57 UTC, JoanneBogart commented on notebooks/dc2/truth_variable_info.ipynb
> +    "Even with this filter, the cell below will take a while to run. If runtime is a concern, you may want to use the SQL database that we also provide to access these information instead."
Change "these information" to "this information"

2022-06-08 00:57 UTC, JoanneBogart commented on notebooks/dc2/truth_variable_info.ipynb
> +    "Now we have the light curves! You might notice that we used `delta_flux` to get the magnidue. Here `delta_flux` is the flux difference to the inifinite time averaged flux value. For SNe, the inf
magnidue -->.  magnitude

2022-06-08 00:57 UTC, JoanneBogart commented on notebooks/dc2/truth_variable_info.ipynb
> +    "Also, not all stars in this summary table are \"variable\"; some are rather static. The column `above_threshold` tells us if the star is \"variable enough\" to be included in the variability tab
interseting  -->. interesting

2022-06-08 00:57 UTC, JoanneBogart commented on notebooks/dc2/truth_variable_info.ipynb
> +    "Another important difference between stars and supernovae is that for stars, their infinite time-averaged fluxes are usualy non-zero! We can verify that:"
usualy --> usually

2022-06-08 00:57 UTC, JoanneBogart commented on notebooks/dc2/truth_variable_info.ipynb
> +    "Again, recall that in the \"variability table\", each row corresponds to one measurement, and we need to collect all the rows that have `id` values overlap with `objects_to_plot[\"id\"].values`.
overlap    --> overlapping

2022-06-08 00:57 UTC, JoanneBogart commented on notebooks/dc2/truth_variable_info.ipynb
> +    "Also remember that the variability table is a large table (even larger in the star case). We will use the same `filters` trick again to reduce the memory footprint, but the cell below will still
these information  --> this information

2022-06-08 00:57 UTC, JoanneBogart commented on notebooks/dc2/truth_variable_info.ipynb
> +    "Once we collect the light curve infomation in `d_lc`. We can use the same `groupby` trick to split the data frame by ID and bandpass, and proceed to make light curve plot."
Add "a" or "the" before "light curve plot".    E.g.,
..and proceed to make the light curve plot

2022-06-08 19:47 UTC, yymao commented
@JoanneBogart thanks for the review. I've addressed all the comments. You can see the detail changed in commit e8e087d. Regarding making the variability in the first star plot more evident: the second variability plot (difference in magnitude) is meant to address the issue. So instead of changing the plot, I just updated the text to make this point more explicit. 

I've also tested the truth_match notebook and everything works fine. Numpy is deprecating the use `np.int` in favor of `np.int64` so I made that change in cba6c3d.

Ready for re-review.

2022-06-08 20:34 UTC, JoanneBogart approved these changes
LGTM.

2022-06-08 20:42 UTC, merged